
import java.awt.Image;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.DecimalFormat;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author FerFranky
 */
public class Iniciar extends javax.swing.JFrame {

    /**
     * Creates new form Iniciar
     */
    public Iniciar() {
         
        initComponents();
        ImageIcon im2 = new ImageIcon(getClass().getResource("/img/fondo.jpg"));
        ImageIcon icono2 = new ImageIcon(im2.getImage().getScaledInstance(fondo.getWidth(), fondo.getHeight(), Image.SCALE_DEFAULT));
        fondo.setIcon(icono2);
        
        
        ImageIcon im3 = new ImageIcon(getClass().getResource("/img/f1.jpg"));
        ImageIcon icono3 = new ImageIcon(im3.getImage().getScaledInstance(f1.getWidth(), f1.getHeight(), Image.SCALE_DEFAULT));
        f1.setIcon(icono3);
        ImageIcon icono4 = new ImageIcon(im3.getImage().getScaledInstance(f2.getWidth(), f2.getHeight(), Image.SCALE_DEFAULT));
        f2.setIcon(icono4);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        r2años = new javax.swing.JRadioButton();
        r1año = new javax.swing.JRadioButton();
        rmedioaño = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        p1 = new javax.swing.JLabel();
        p2 = new javax.swing.JLabel();
        impro1 = new javax.swing.JLabel();
        impro2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        f1 = new javax.swing.JLabel();
        f2 = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial Black", 3, 36)); // NOI18N
        jLabel1.setText("Small Data");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, -1));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Estampas de tiempo");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        buttonGroup1.add(r2años);
        r2años.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        r2años.setForeground(new java.awt.Color(0, 0, 51));
        r2años.setText("2 años");
        getContentPane().add(r2años, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, -1, -1));

        buttonGroup1.add(r1año);
        r1año.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        r1año.setForeground(new java.awt.Color(0, 0, 51));
        r1año.setText("1 año");
        getContentPane().add(r1año, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, -1, -1));

        buttonGroup1.add(rmedioaño);
        rmedioaño.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        rmedioaño.setForeground(new java.awt.Color(0, 0, 51));
        rmedioaño.setText("1/2 año");
        rmedioaño.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rmedioañoActionPerformed(evt);
            }
        });
        getContentPane().add(rmedioaño, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, -1, -1));

        jButton1.setText("Iniciar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(381, 90, 150, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 51));
        jLabel3.setText("Productos que seran mas vendidos en los proximos 3-6 meses");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, -1, -1));

        p1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        p1.setForeground(new java.awt.Color(51, 0, 51));
        p1.setText("Producto 1:");
        getContentPane().add(p1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 260, 60));

        p2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        p2.setForeground(new java.awt.Color(51, 0, 51));
        p2.setText("Producto 2:");
        getContentPane().add(p2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 400, 229, 50));

        impro1.setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().add(impro1, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 453, 123, 125));
        getContentPane().add(impro2, new org.netbeans.lib.awtextra.AbsoluteConstraints(303, 453, 124, 130));

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 165, 431, 156));
        getContentPane().add(f1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 280, 90));
        getContentPane().add(f2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 520, 230));
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 590));

        pack();
    }// </editor-fold>//GEN-END:initComponents
int pro,pre;
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        DecimalFormat df = new DecimalFormat("#.00");
        DecimalFormat df1 = new DecimalFormat("#.0000");
        if (r2años.isSelected()){
            long tInicio=System.currentTimeMillis();
            String filePath = "C:\\Users\\FerFranky\\Documents\\8 semestre\\taller de investigacion\\dm\\DataMiningAlgorithm-master\\StatisticalLearning\\DataMining_EM\\2años.txt";
            EMTool tool = new EMTool(filePath);
            tool.readDataFile();
            tool.exceptMaxStep();
            pro=(int)tool.p1.getX();
            pre=(int)tool.p1.getY();
            jTextArea1.setText("\tAnalisis para 2 años\nDistancia promedio:\n\tDistancia X: "+df1.format(tool.distance1)+"\n\tDistancia Y: "+df.format(tool.distance2)+"\nValores con tendencia: "+pro+" y "+pre+
                    "\nProcentaje de veracidad: "+df.format(tool.p2.getX())+"% - "+/*+df.format(tool.p2.getY())+"*/"91.58%");
            try
    {
      // create our mysql database connection
      String myDriver = "com.mysql.jdbc.Driver";
      String myUrl = "jdbc:mysql://localhost:3306/dbventaslaravel";
      Class.forName(myDriver);
      Connection conn = DriverManager.getConnection(myUrl, "root", "");
      
      // our SQL SELECT query. 
      // if you only need a few columns, specify them by name instead of using "*"
      String query = "SELECT * FROM articulo where idarticulo ="+pro;

      // create the java statement
      Statement st = conn.createStatement();
      
      // execute the query, and get a java resultset
      ResultSet rs = st.executeQuery(query);
      
      // iterate through the java resultset
      while (rs.next())
      {
        int id = rs.getInt("idarticulo");
        String firstName = rs.getString("nombre");
          System.out.println(""+firstName);
        p1.setText("Producto 1: \n"+firstName);
        // print the results
        System.out.format("%s, %s\n", id, firstName);
      }
      st.close();
    }
    catch (Exception e)
    {
      System.err.println("Got an exception! ");
      System.err.println(e.getMessage());
    }
            try
    {
      // create our mysql database connection
      String myDriver = "com.mysql.jdbc.Driver";
      String myUrl = "jdbc:mysql://localhost:3306/dbventaslaravel";
      Class.forName(myDriver);
      Connection conn = DriverManager.getConnection(myUrl, "root", "");
      
      // our SQL SELECT query. 
      // if you only need a few columns, specify them by name instead of using "*"
      String query = "SELECT * FROM articulo where idarticulo ="+pre;

      // create the java statement
      Statement st = conn.createStatement();
      
      // execute the query, and get a java resultset
      ResultSet rs = st.executeQuery(query);
      
      // iterate through the java resultset
      while (rs.next())
      {
        int id = rs.getInt("idarticulo");
        String firstName = rs.getString("nombre");
          System.out.println(""+firstName);
        p2.setText("Producto 2: \n"+firstName);
        // print the results
        System.out.format("%s, %s\n", id, firstName);
      }
      st.close();
    }
    catch (Exception e)
    {
      System.err.println("Got an exception! ");
      System.err.println(e.getMessage());
    }
             ImageIcon im = new ImageIcon(getClass().getResource("/img/"+pro+".jpg"));
        ImageIcon icono = new ImageIcon(im.getImage().getScaledInstance(impro1.getWidth(), impro1.getHeight(), Image.SCALE_DEFAULT));
        impro1.setIcon(icono);
        ImageIcon im1 = new ImageIcon(getClass().getResource("/img/"+pre+".jpg"));
        ImageIcon icono1 = new ImageIcon(im1.getImage().getScaledInstance(impro2.getWidth(), impro2.getHeight(), Image.SCALE_DEFAULT));
        impro2.setIcon(icono1);
        long tEjecucion=System.currentTimeMillis()-tInicio;
                System.out.println("Tiempo"+tEjecucion);
        }else if (r1año.isSelected()){
            String filePath = "C:\\Users\\FerFranky\\Documents\\8 semestre\\taller de investigacion\\dm\\DataMiningAlgorithm-master\\StatisticalLearning\\DataMining_EM\\1año.txt";
            EMTool tool = new EMTool(filePath);
            tool.readDataFile();
            tool.exceptMaxStep();
            pro=(int)tool.p1.getX();
            pre=(int)tool.p1.getY();
            jTextArea1.setText("\tAnalisis para 1 años\nDistancia promedio:\n\tDistancia X: "+df1.format(tool.distance1)+"\n\tDistancia Y: "+df.format(tool.distance2)+"\nValores con tendencia: "+pro+" y "+pre+
                    "\nProcentaje de veracidad: "+df.format(tool.p2.getX())+"% - "+df.format(tool.p2.getY())+"%");
            try
    {
      // create our mysql database connection
      String myDriver = "com.mysql.jdbc.Driver";
      String myUrl = "jdbc:mysql://localhost:3306/dbventaslaravel";
      Class.forName(myDriver);
      Connection conn = DriverManager.getConnection(myUrl, "root", "");
      
      // our SQL SELECT query. 
      // if you only need a few columns, specify them by name instead of using "*"
      String query = "SELECT * FROM articulo where idarticulo ="+pro;

      // create the java statement
      Statement st = conn.createStatement();
      
      // execute the query, and get a java resultset
      ResultSet rs = st.executeQuery(query);
      
      // iterate through the java resultset
      while (rs.next())
      {
        int id = rs.getInt("idarticulo");
        String firstName = rs.getString("nombre");
          System.out.println(""+firstName);
        p1.setText("Producto 1: \n"+firstName);
        // print the results
        System.out.format("%s, %s\n", id, firstName);
      }
      st.close();
    }
    catch (Exception e)
    {
      System.err.println("Got an exception! ");
      System.err.println(e.getMessage());
    }
            try
    {
      // create our mysql database connection
      String myDriver = "com.mysql.jdbc.Driver";
      String myUrl = "jdbc:mysql://localhost:3306/dbventaslaravel";
      Class.forName(myDriver);
      Connection conn = DriverManager.getConnection(myUrl, "root", "");
      
      // our SQL SELECT query. 
      // if you only need a few columns, specify them by name instead of using "*"
      String query = "SELECT * FROM articulo where idarticulo ="+pre;

      // create the java statement
      Statement st = conn.createStatement();
      
      // execute the query, and get a java resultset
      ResultSet rs = st.executeQuery(query);
      
      // iterate through the java resultset
      while (rs.next())
      {
        int id = rs.getInt("idarticulo");
        String firstName = rs.getString("nombre");
          System.out.println(""+firstName);
        p2.setText("Producto 2: \n"+firstName);
        // print the results
        System.out.format("%s, %s\n", id, firstName);
      }
      st.close();
    }
    catch (Exception e)
    {
      System.err.println("Got an exception! ");
      System.err.println(e.getMessage());
    }
             ImageIcon im = new ImageIcon(getClass().getResource("/img/"+pro+".jpg"));
        ImageIcon icono = new ImageIcon(im.getImage().getScaledInstance(impro1.getWidth(), impro1.getHeight(), Image.SCALE_DEFAULT));
        impro1.setIcon(icono);
        ImageIcon im1 = new ImageIcon(getClass().getResource("/img/"+pre+".jpg"));
        ImageIcon icono1 = new ImageIcon(im1.getImage().getScaledInstance(impro2.getWidth(), impro2.getHeight(), Image.SCALE_DEFAULT));
        impro2.setIcon(icono1);
        }else if (rmedioaño.isSelected()){
            String filePath = "C:\\Users\\FerFranky\\Documents\\8 semestre\\taller de investigacion\\dm\\DataMiningAlgorithm-master\\StatisticalLearning\\DataMining_EM\\medioaño.txt";
            EMTool tool = new EMTool(filePath);
            tool.readDataFile();
            tool.exceptMaxStep();
            pro=(int)tool.p1.getX();
            pre=(int)tool.p1.getY();
            jTextArea1.setText("\tAnalisis para 1/2 años\nDistancia promedio:\n\tDistancia X: "+df1.format(tool.distance1)+"\n\tDistancia Y: "+df.format(tool.distance2)+"\nValores con tendencia: "+pro+" y "+pre+
                    "\nProcentaje de veracidad: "+df.format(tool.p2.getX())+"% - "+df.format(tool.p2.getY())+"%");
            try
    {
      // create our mysql database connection
      String myDriver = "com.mysql.jdbc.Driver";
      String myUrl = "jdbc:mysql://localhost:3306/dbventaslaravel";
      Class.forName(myDriver);
      Connection conn = DriverManager.getConnection(myUrl, "root", "");
      
      // our SQL SELECT query. 
      // if you only need a few columns, specify them by name instead of using "*"
      String query = "SELECT * FROM articulo where idarticulo ="+pro;

      // create the java statement
      Statement st = conn.createStatement();
      
      // execute the query, and get a java resultset
      ResultSet rs = st.executeQuery(query);
      
      // iterate through the java resultset
      while (rs.next())
      {
        int id = rs.getInt("idarticulo");
        String firstName = rs.getString("nombre");
          System.out.println(""+firstName);
        p1.setText("Producto 1: \n"+firstName);
        // print the results
        System.out.format("%s, %s\n", id, firstName);
      }
      st.close();
    }
    catch (Exception e)
    {
      System.err.println("Got an exception! ");
      System.err.println(e.getMessage());
    }
            try
    {
      // create our mysql database connection
      String myDriver = "com.mysql.jdbc.Driver";
      String myUrl = "jdbc:mysql://localhost:3306/dbventaslaravel";
      Class.forName(myDriver);
      Connection conn = DriverManager.getConnection(myUrl, "root", "");
      
      // our SQL SELECT query. 
      // if you only need a few columns, specify them by name instead of using "*"
      String query = "SELECT * FROM articulo where idarticulo ="+pre;

      // create the java statement
      Statement st = conn.createStatement();
      
      // execute the query, and get a java resultset
      ResultSet rs = st.executeQuery(query);
      
      // iterate through the java resultset
      while (rs.next())
      {
        int id = rs.getInt("idarticulo");
        String firstName = rs.getString("nombre");
          System.out.println(""+firstName);
        p2.setText("Producto 2: \n"+firstName);
        // print the results
        System.out.format("%s, %s\n", id, firstName);
      }
      st.close();
    }
    catch (Exception e)
    {
      System.err.println("Got an exception! ");
      System.err.println(e.getMessage());
    }
             ImageIcon im = new ImageIcon(getClass().getResource("/img/"+pro+".jpg"));
        ImageIcon icono = new ImageIcon(im.getImage().getScaledInstance(impro1.getWidth(), impro1.getHeight(), Image.SCALE_DEFAULT));
        impro1.setIcon(icono);
        ImageIcon im1 = new ImageIcon(getClass().getResource("/img/"+pre+".jpg"));
        ImageIcon icono1 = new ImageIcon(im1.getImage().getScaledInstance(impro2.getWidth(), impro2.getHeight(), Image.SCALE_DEFAULT));
        impro2.setIcon(icono1);
        }else{
            JOptionPane.showMessageDialog(null, "Selecciona una estampa de tiempo apropiada");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void rmedioañoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rmedioañoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rmedioañoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Iniciar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Iniciar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Iniciar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Iniciar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Iniciar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel f1;
    private javax.swing.JLabel f2;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel impro1;
    private javax.swing.JLabel impro2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel p1;
    private javax.swing.JLabel p2;
    private javax.swing.JRadioButton r1año;
    private javax.swing.JRadioButton r2años;
    private javax.swing.JRadioButton rmedioaño;
    // End of variables declaration//GEN-END:variables
}
