
import java.awt.Image;
import java.io.BufferedReader;
import java.io.FileReader;
import javax.swing.ImageIcon;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author FerFranky
 */
public class Chatbot extends javax.swing.JFrame {

    /**
     * Creates new form Chatbot
     */
    public Chatbot() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        chat = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        yo = new javax.swing.JTextField();
        titulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("interfaz"); // NOI18N

        chat.setEditable(false);
        chat.setBackground(new java.awt.Color(0, 0, 102));
        chat.setColumns(20);
        chat.setFont(new java.awt.Font("Monospaced", 3, 14)); // NOI18N
        chat.setForeground(new java.awt.Color(255, 255, 153));
        chat.setRows(5);
        jScrollPane1.setViewportView(chat);

        jButton1.setBackground(new java.awt.Color(255, 0, 0));
        jButton1.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Enviar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        yo.setBackground(new java.awt.Color(102, 0, 102));
        yo.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        yo.setForeground(new java.awt.Color(255, 255, 204));

        titulo.setBackground(new java.awt.Color(255, 255, 51));
        titulo.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        titulo.setForeground(new java.awt.Color(102, 0, 102));
        titulo.setText("Chatbot sobre Inteligencia Artificial");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(yo, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(titulo, javax.swing.GroupLayout.DEFAULT_SIZE, 532, Short.MAX_VALUE)
                        .addComponent(jScrollPane1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(titulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(yo, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
              BaseDatos b= new BaseDatos();
        String cadena="";
        if(yo.getText().toLowerCase().contains(b.preguntas[0])
                ||yo.getText().toLowerCase().contains(b.preguntas[1])
                ||yo.getText().toLowerCase().contains(b.preguntas[2])
                ||yo.getText().toLowerCase().contains(b.preguntas[3])
                ||yo.getText().toLowerCase().contains(b.preguntas[4])){
            chat.setText(chat.getText()+"\n\nYo=> "+yo.getText());
            int resp = (int) (Math.random()*3+1);
                    if(resp == 1){
                        cadena="El => "+b.respuestas[0];
                    }else if(resp == 2){
                        cadena="El => "+b.respuestas[1];
                    }else if(resp == 3){
                        cadena="El => "+b.respuestas[2];
                    }      
            chat.setText(chat.getText()+"\n"+cadena);
                }
        else if(yo.getText().toLowerCase().contains(b.preguntas[5])||yo.getText().toLowerCase().contains(b.preguntas[6])||yo.getText().toLowerCase().contains(b.preguntas[7])){
            chat.setText(chat.getText()+"\n\nYo=> "+yo.getText());
            int resp1 = (int) (Math.random()*3+1);
                    if(resp1 == 1){
                        cadena="El => "+b.respuestas[3];
                    }else if(resp1 == 2){
                        cadena="El => "+b.respuestas[4];
                    }else if(resp1 == 3){
                        cadena="El => "+b.respuestas[5];
                    }      
            chat.setText(chat.getText()+"\n"+cadena);
                }
        else if(yo.getText().toLowerCase().contains(b.preguntas[8])||yo.getText().toLowerCase().contains(b.preguntas[9])||yo.getText().toLowerCase().contains(b.preguntas[10])||yo.getText().toLowerCase().contains(b.preguntas[11])){
            chat.setText(chat.getText()+"\n\nYo=> "+yo.getText());
            int resp1 = (int) (Math.random()*3+1);
                    if(resp1 == 1){
                        cadena="El => "+b.respuestas[6];
                    }else if(resp1 == 2){
                        cadena="El => "+b.respuestas[7];
                    }else if(resp1 == 3){
                        cadena="El => "+b.respuestas[8];
                    }      
            chat.setText(chat.getText()+"\n"+cadena);
                }
        else if(yo.getText().toLowerCase().contains(b.preguntas[12])||yo.getText().toLowerCase().contains(b.preguntas[13])||yo.getText().toLowerCase().contains(b.preguntas[14])){
            chat.setText(chat.getText()+"\n\nYo=> "+yo.getText());
            int resp1 = (int) (Math.random()*2+1);
                    if(resp1 == 1){
                        cadena="El => "+b.respuestas[9];
                    }else if(resp1 == 2){
                        cadena="El => "+b.respuestas[10];
                    
                    }     
            chat.setText(chat.getText()+"\n"+cadena);
                }
        else if(yo.getText().toLowerCase().contains(b.preguntas[15])||yo.getText().toLowerCase().contains(b.preguntas[16])||yo.getText().toLowerCase().contains(b.preguntas[17])){
            chat.setText(chat.getText()+"\n\nYo=> "+yo.getText());
            int resp1 = (int) (Math.random()*2+1);
                    if(resp1 == 1){
                        cadena="El => "+b.respuestas[11];
                    }else if(resp1 == 2){
                        cadena="El => "+b.respuestas[12];
                    }
            chat.setText(chat.getText()+"\n"+cadena);
                }
        else if(yo.getText().toLowerCase().contains(b.preguntas[18])||yo.getText().toLowerCase().contains(b.preguntas[19])){
            chat.setText(chat.getText()+"\n\nYo=> "+yo.getText());
            
                        cadena="El => "+b.respuestas[13];
                   
                        
                    
            chat.setText(chat.getText()+"\n"+cadena);
                }else if(yo.getText().toLowerCase().contains(b.preguntas[20])||yo.getText().toLowerCase().contains(b.preguntas[21])||yo.getText().toLowerCase().contains(b.preguntas[22])){
            chat.setText(chat.getText()+"\n\nYo=> "+yo.getText());
            
                        cadena="El => "+b.respuestas[14];
                   
                        
                    
            chat.setText(chat.getText()+"\n"+cadena);
                }else if(yo.getText().toLowerCase().contains(b.preguntas[23])){
            chat.setText(chat.getText()+"\n\nYo=> "+yo.getText());
            
                        cadena="El => "+b.respuestas[15];
                   
                        
                    
            chat.setText(chat.getText()+"\n"+cadena);
                }else if(yo.getText().toLowerCase().contains(b.preguntas[24])||yo.getText().toLowerCase().contains(b.preguntas[25])){
            chat.setText(chat.getText()+"\n\nYo=> "+yo.getText());
            
                        cadena="El => "+b.respuestas[16];
                   
                        
                    
            chat.setText(chat.getText()+"\n"+cadena);
                }else if(yo.getText().toLowerCase().contains(b.preguntas[26])||yo.getText().toLowerCase().contains(b.preguntas[27])){
            chat.setText(chat.getText()+"\n\nYo=> "+yo.getText());
            
                        cadena="El => "+b.respuestas[17];
                   
                        
                    
            chat.setText(chat.getText()+"\n"+cadena);
                }else if(yo.getText().toLowerCase().contains(b.preguntas[28])){
            chat.setText(chat.getText()+"\n\nYo=> "+yo.getText());
            
                        cadena="El => "+b.respuestas[18];
                   
                        
                    
            chat.setText(chat.getText()+"\n"+cadena);
                }else if(yo.getText().toLowerCase().contains(b.preguntas[29])){
            chat.setText(chat.getText()+"\n\nYo=> "+yo.getText());
            
                        cadena="El => "+b.respuestas[19];
                   
                        
                    
            chat.setText(chat.getText()+"\n"+cadena);
                }else if(yo.getText().toLowerCase().contains(b.preguntas[30])||yo.getText().toLowerCase().contains(b.preguntas[31])||yo.getText().toLowerCase().contains(b.preguntas[32])){
            chat.setText(chat.getText()+"\n\nYo=> "+yo.getText());
            
                        cadena="El => "+b.respuestas[20];
                   
                        
                    
            chat.setText(chat.getText()+"\n"+cadena);
                }else if(yo.getText().toLowerCase().contains(b.preguntas[33])||yo.getText().toLowerCase().contains(b.preguntas[34])){
            chat.setText(chat.getText()+"\n\nYo=> "+yo.getText());
            
                        cadena="El => "+b.respuestas[21];
                   
                        
                    
            chat.setText(chat.getText()+"\n"+cadena);
                }else if(yo.getText().toLowerCase().contains(b.preguntas[35])){
            chat.setText(chat.getText()+"\n\nYo=> "+yo.getText());
            
                        cadena="El => "+b.respuestas[22];
                   
                        
                    
            chat.setText(chat.getText()+"\n"+cadena);
                }else if(yo.getText().toLowerCase().contains(b.preguntas[36])){
            chat.setText(chat.getText()+"\n\nYo=> "+yo.getText());
            
                        cadena="El => "+b.respuestas[23];
                   
                        
                    
            chat.setText(chat.getText()+"\n"+cadena);
                }else if(yo.getText().toLowerCase().contains(b.preguntas[37])){
            chat.setText(chat.getText()+"\n\nYo=> "+yo.getText());
            
                        cadena="El => "+b.respuestas[24];
                   
                        
                    
            chat.setText(chat.getText()+"\n"+cadena);
                }else if(yo.getText().toLowerCase().contains(b.preguntas[38])||yo.getText().toLowerCase().contains(b.preguntas[39])){
            chat.setText(chat.getText()+"\n\nYo=> "+yo.getText());
            
                        cadena="El => "+b.respuestas[25];
                   
                        
                    
            chat.setText(chat.getText()+"\n"+cadena);
                }else if(yo.getText().toLowerCase().contains(b.preguntas[40])||yo.getText().toLowerCase().contains(b.preguntas[41])){
            chat.setText(chat.getText()+"\n\nYo=> "+yo.getText());
            
                        cadena="El => "+b.respuestas[26];
                   
                        
                    
            chat.setText(chat.getText()+"\n"+cadena);
                }else if(yo.getText().toLowerCase().contains(b.preguntas[42])||yo.getText().toLowerCase().contains(b.preguntas[43])){
            chat.setText(chat.getText()+"\n\nYo=> "+yo.getText());
            
                        cadena="El => "+b.respuestas[26];
                   
                        
                    
            chat.setText(chat.getText()+"\n"+cadena);
                }
        else{
            cadena="El => No entiendo";
            chat.setText(chat.getText()+"\n\nYo=> "+yo.getText());
            chat.setText(chat.getText()+"\n"+cadena);
        } 
        yo.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Chatbot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Chatbot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Chatbot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Chatbot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Chatbot().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea chat;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel titulo;
    private javax.swing.JTextField yo;
    // End of variables declaration//GEN-END:variables
}
