
import java.util.Random;
import javax.swing.JOptionPane;

public class cuadro extends javax.swing.JFrame {
int intentos;
    public cuadro() {
        initComponents();
        setSize(430,500);
        setLocationRelativeTo(null);
        jButton16.setVisible(false);
        Random generadorAleatorios = new Random();
        int arre[]=new int[15];
        int t=0;
    int cont;
    int i,comp=0;
    
    cont=0;
while(t<=100){    
    int numeroAleatorio = 1+generadorAleatorios.nextInt(15);
    if(t==0){
        arre[cont]=numeroAleatorio;
        System.out.println(t+" no: "+arre[cont]);
        cont++;
    }else if(t>0){
        for(i=0;i<=cont;i++){
            if(numeroAleatorio==arre[i]){
                comp=1;
            }
        }
        if(comp==0){
            arre[cont]=numeroAleatorio;
            System.out.println(cont+" no: "+arre[cont]);
            comp=0;      
            cont++;
            if(cont==15){
                t=100;
            }
        }
        comp=0;
    }
  t++;
}
jButton1.setText(Integer.toString(arre[0]));
jButton2.setText(Integer.toString(arre[1]));
jButton3.setText(Integer.toString(arre[2]));
jButton4.setText(Integer.toString(arre[3]));
jButton5.setText(Integer.toString(arre[4]));
jButton6.setText(Integer.toString(arre[5]));
jButton7.setText(Integer.toString(arre[6]));
jButton8.setText(Integer.toString(arre[7]));
jButton9.setText(Integer.toString(arre[8]));
jButton10.setText(Integer.toString(arre[9]));
jButton11.setText(Integer.toString(arre[10]));
jButton12.setText(Integer.toString(arre[11]));
jButton13.setText(Integer.toString(arre[12]));
jButton14.setText(Integer.toString(arre[13]));
jButton15.setText(Integer.toString(arre[14]));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Goudy Stout", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(70, 145, 59, 74);

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setFont(new java.awt.Font("Goudy Stout", 0, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(143, 145, 59, 74);

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setFont(new java.awt.Font("Goudy Stout", 0, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("3");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(212, 145, 59, 74);

        jButton4.setBackground(new java.awt.Color(0, 0, 0));
        jButton4.setFont(new java.awt.Font("Goudy Stout", 0, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("4");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(281, 145, 59, 74);

        jButton5.setBackground(new java.awt.Color(0, 0, 0));
        jButton5.setFont(new java.awt.Font("Goudy Stout", 0, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("5");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(70, 225, 59, 74);

        jButton6.setBackground(new java.awt.Color(0, 0, 0));
        jButton6.setFont(new java.awt.Font("Goudy Stout", 0, 14)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("6");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(140, 225, 59, 74);

        jButton7.setBackground(new java.awt.Color(0, 0, 0));
        jButton7.setFont(new java.awt.Font("Goudy Stout", 0, 14)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("7");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7);
        jButton7.setBounds(210, 225, 59, 74);

        jButton8.setBackground(new java.awt.Color(0, 0, 0));
        jButton8.setFont(new java.awt.Font("Goudy Stout", 0, 14)); // NOI18N
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setText("8");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8);
        jButton8.setBounds(280, 225, 59, 74);

        jButton9.setBackground(new java.awt.Color(0, 0, 0));
        jButton9.setFont(new java.awt.Font("Goudy Stout", 0, 14)); // NOI18N
        jButton9.setForeground(new java.awt.Color(255, 255, 255));
        jButton9.setText("9");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9);
        jButton9.setBounds(70, 305, 59, 74);

        jButton10.setBackground(new java.awt.Color(0, 0, 0));
        jButton10.setFont(new java.awt.Font("Goudy Stout", 0, 14)); // NOI18N
        jButton10.setForeground(new java.awt.Color(255, 255, 255));
        jButton10.setText("10");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton10);
        jButton10.setBounds(140, 305, 59, 74);

        jButton11.setBackground(new java.awt.Color(0, 0, 0));
        jButton11.setFont(new java.awt.Font("Goudy Stout", 0, 14)); // NOI18N
        jButton11.setForeground(new java.awt.Color(255, 255, 255));
        jButton11.setText("11");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton11);
        jButton11.setBounds(210, 305, 59, 74);

        jButton12.setBackground(new java.awt.Color(0, 0, 0));
        jButton12.setFont(new java.awt.Font("Goudy Stout", 0, 14)); // NOI18N
        jButton12.setForeground(new java.awt.Color(255, 255, 255));
        jButton12.setText("12");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton12);
        jButton12.setBounds(280, 305, 59, 74);

        jButton13.setBackground(new java.awt.Color(0, 0, 0));
        jButton13.setFont(new java.awt.Font("Goudy Stout", 0, 14)); // NOI18N
        jButton13.setForeground(new java.awt.Color(255, 255, 255));
        jButton13.setText("13");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton13);
        jButton13.setBounds(70, 385, 59, 74);

        jButton14.setBackground(new java.awt.Color(0, 0, 0));
        jButton14.setFont(new java.awt.Font("Goudy Stout", 0, 14)); // NOI18N
        jButton14.setForeground(new java.awt.Color(255, 255, 255));
        jButton14.setText("14");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton14);
        jButton14.setBounds(140, 385, 59, 74);

        jButton15.setBackground(new java.awt.Color(0, 0, 0));
        jButton15.setFont(new java.awt.Font("Goudy Stout", 0, 14)); // NOI18N
        jButton15.setForeground(new java.awt.Color(255, 255, 255));
        jButton15.setText("15");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton15);
        jButton15.setBounds(210, 385, 59, 74);

        jButton16.setBackground(new java.awt.Color(0, 0, 0));
        jButton16.setFont(new java.awt.Font("Goudy Stout", 0, 14)); // NOI18N
        jButton16.setForeground(new java.awt.Color(255, 255, 255));
        jButton16.setText("16");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton16);
        jButton16.setBounds(280, 385, 59, 74);

        jButton17.setBackground(new java.awt.Color(255, 255, 102));
        jButton17.setForeground(new java.awt.Color(102, 0, 102));
        jButton17.setText("Reiniciar");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton17);
        jButton17.setBounds(80, 90, 240, 23);

        jLabel1.setFont(new java.awt.Font("Ravie", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 0, 102));
        jLabel1.setText("Cuadro Magico");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 11, 352, 49);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
intentos++;
System.out.println("Intento no: "+intentos);
        if(jButton5.isVisible()==false){
        jButton5.setText(jButton1.getText());
        jButton1.setVisible(false);
        jButton5.setVisible(true);
        }else if(jButton2.isVisible()==false){
        jButton2.setText(jButton1.getText());
        jButton1.setVisible(false);
        jButton2.setVisible(true);
        }
        if(jButton1.getText().equals("1")&&jButton2.getText().equals("2")&&jButton3.getText().equals("3")&&jButton4.getText().equals("4")){
    JOptionPane.showMessageDialog(this, "Linea 1 completa \n No de intentos: "+intentos);
}
if(jButton1.getText().equals("1")&&jButton2.getText().equals("2")&&jButton3.getText().equals("3")&&jButton4.getText().equals("4")&&jButton5.getText().equals("5")&&jButton6.getText().equals("6")&&jButton7.getText().equals("7")&&jButton8.getText().equals("8")&&jButton9.getText().equals("9")&&jButton10.getText().equals("10")&&jButton11.getText().equals("11")&&jButton12.getText().equals("12")&&jButton13.getText().equals("13")&&jButton14.getText().equals("14")&&jButton15.getText().equals("15")){
    JOptionPane.showMessageDialog(this, "Ganaste \n No de intentos: "+intentos);
}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        intentos++;
        System.out.println("Intento no: "+intentos);
        if(jButton9.isVisible()==false){
        jButton9.setText(jButton10.getText());
        jButton10.setVisible(false);
        jButton9.setVisible(true);
        }else if(jButton11.isVisible()==false){
        jButton11.setText(jButton10.getText());
        jButton10.setVisible(false);
        jButton11.setVisible(true);
        }else if(jButton14.isVisible()==false){
        jButton14.setText(jButton10.getText());
        jButton10.setVisible(false);
        jButton14.setVisible(true);
        }else if(jButton6.isVisible()==false){
        jButton6.setText(jButton10.getText());
        jButton10.setVisible(false);
        jButton6.setVisible(true);
        }
        
 if(jButton1.getText().equals("1")&&jButton2.getText().equals("2")&&jButton3.getText().equals("3")&&jButton4.getText().equals("4")){
    JOptionPane.showMessageDialog(this, "Linea 1 completa \n No de intentos: "+intentos);
}
if(jButton1.getText().equals("1")&&jButton2.getText().equals("2")&&jButton3.getText().equals("3")&&jButton4.getText().equals("4")&&jButton5.getText().equals("5")&&jButton6.getText().equals("6")&&jButton7.getText().equals("7")&&jButton8.getText().equals("8")&&jButton9.getText().equals("9")&&jButton10.getText().equals("10")&&jButton11.getText().equals("11")&&jButton12.getText().equals("12")&&jButton13.getText().equals("13")&&jButton14.getText().equals("14")&&jButton15.getText().equals("15")){
    JOptionPane.showMessageDialog(this, "Ganaste \n No de intentos: "+intentos);
}
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:
        intentos++;
        System.out.println("Intento no: "+intentos);
        if(jButton10.isVisible()==false){
        jButton10.setText(jButton14.getText());
        jButton14.setVisible(false);
        jButton10.setVisible(true);
        }else if(jButton13.isVisible()==false){
        jButton13.setText(jButton14.getText());
        jButton14.setVisible(false);
        jButton13.setVisible(true);
        }if(jButton15.isVisible()==false){
        jButton15.setText(jButton14.getText());
        jButton14.setVisible(false);
        jButton15.setVisible(true);
        }
        
 if(jButton1.getText().equals("1")&&jButton2.getText().equals("2")&&jButton3.getText().equals("3")&&jButton4.getText().equals("4")){
    JOptionPane.showMessageDialog(this, "Linea 1 completa \n No de intentos: "+intentos);
}
if(jButton1.getText().equals("1")&&jButton2.getText().equals("2")&&jButton3.getText().equals("3")&&jButton4.getText().equals("4")&&jButton5.getText().equals("5")&&jButton6.getText().equals("6")&&jButton7.getText().equals("7")&&jButton8.getText().equals("8")&&jButton9.getText().equals("9")&&jButton10.getText().equals("10")&&jButton11.getText().equals("11")&&jButton12.getText().equals("12")&&jButton13.getText().equals("13")&&jButton14.getText().equals("14")&&jButton15.getText().equals("15")){
    JOptionPane.showMessageDialog(this, "Ganaste \n No de intentos: "+intentos);
}
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        intentos++;
        System.out.println("Intento no: "+intentos);
        if(jButton5.isVisible()==false){
        jButton5.setText(jButton9.getText());
        jButton9.setVisible(false);
        jButton5.setVisible(true);
        }else if(jButton10.isVisible()==false){
        jButton10.setText(jButton9.getText());
        jButton9.setVisible(false);
        jButton10.setVisible(true);
        }if(jButton13.isVisible()==false){
        jButton13.setText(jButton9.getText());
        jButton9.setVisible(false);
        jButton13.setVisible(true);
        }
        
 if(jButton1.getText().equals("1")&&jButton2.getText().equals("2")&&jButton3.getText().equals("3")&&jButton4.getText().equals("4")){
    JOptionPane.showMessageDialog(this, "Linea 1 completa \n No de intentos: "+intentos);
}
if(jButton1.getText().equals("1")&&jButton2.getText().equals("2")&&jButton3.getText().equals("3")&&jButton4.getText().equals("4")&&jButton5.getText().equals("5")&&jButton6.getText().equals("6")&&jButton7.getText().equals("7")&&jButton8.getText().equals("8")&&jButton9.getText().equals("9")&&jButton10.getText().equals("10")&&jButton11.getText().equals("11")&&jButton12.getText().equals("12")&&jButton13.getText().equals("13")&&jButton14.getText().equals("14")&&jButton15.getText().equals("15")){
    JOptionPane.showMessageDialog(this, "Ganaste \n No de intentos: "+intentos);
}
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
        intentos++;
        System.out.println("Intento no: "+intentos);
        if(jButton16.isVisible()==false){
        jButton16.setText(jButton12.getText());
        jButton12.setVisible(false);
        jButton16.setVisible(true);
        }else if(jButton11.isVisible()==false){
            jButton11.setText(jButton12.getText());
        jButton12.setVisible(false);
        jButton11.setVisible(true);
        }else if(jButton8.isVisible()==false){
            jButton8.setText(jButton12.getText());
        jButton12.setVisible(false);
        jButton8.setVisible(true);
        }
        
 if(jButton1.getText().equals("1")&&jButton2.getText().equals("2")&&jButton3.getText().equals("3")&&jButton4.getText().equals("4")){
    JOptionPane.showMessageDialog(this, "Linea 1 completa \n No de intentos: "+intentos);
}
if(jButton1.getText().equals("1")&&jButton2.getText().equals("2")&&jButton3.getText().equals("3")&&jButton4.getText().equals("4")&&jButton5.getText().equals("5")&&jButton6.getText().equals("6")&&jButton7.getText().equals("7")&&jButton8.getText().equals("8")&&jButton9.getText().equals("9")&&jButton10.getText().equals("10")&&jButton11.getText().equals("11")&&jButton12.getText().equals("12")&&jButton13.getText().equals("13")&&jButton14.getText().equals("14")&&jButton15.getText().equals("15")){
    JOptionPane.showMessageDialog(this, "Ganaste \n No de intentos: "+intentos);
}
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        // TODO add your handling code here:
        intentos++;
        System.out.println("Intento no: "+intentos);
        if(jButton16.isVisible()==false){
        jButton16.setText(jButton15.getText());
        jButton15.setVisible(false);
        jButton16.setVisible(true);
        }else if(jButton11.isVisible()==false){
            jButton11.setText(jButton15.getText());
            jButton11.setVisible(true);
            jButton15.setVisible(false);
        }else if(jButton14.isVisible()==false){
            jButton14.setText(jButton15.getText());
            jButton14.setVisible(true);
            jButton15.setVisible(false);
        }
        
 if(jButton1.getText().equals("1")&&jButton2.getText().equals("2")&&jButton3.getText().equals("3")&&jButton4.getText().equals("4")){
    JOptionPane.showMessageDialog(this, "Linea 1 completa \n No de intentos: "+intentos);
}
if(jButton1.getText().equals("1")&&jButton2.getText().equals("2")&&jButton3.getText().equals("3")&&jButton4.getText().equals("4")&&jButton5.getText().equals("5")&&jButton6.getText().equals("6")&&jButton7.getText().equals("7")&&jButton8.getText().equals("8")&&jButton9.getText().equals("9")&&jButton10.getText().equals("10")&&jButton11.getText().equals("11")&&jButton12.getText().equals("12")&&jButton13.getText().equals("13")&&jButton14.getText().equals("14")&&jButton15.getText().equals("15")){
    JOptionPane.showMessageDialog(this, "Ganaste \n No de intentos: "+intentos);
}
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        // TODO add your handling code here:
        intentos++;
        System.out.println("Intento no: "+intentos);
        if(jButton12.isVisible()==false){
        jButton12.setText(jButton16.getText());
        jButton16.setVisible(false);
        jButton12.setVisible(true);
        }else if(jButton15.isVisible()==false){
        jButton15.setText(jButton16.getText());
        jButton16.setVisible(false);
        jButton15.setVisible(true);
        }
        
 
if(jButton1.getText().equals("1")&&jButton2.getText().equals("2")&&jButton3.getText().equals("3")&&jButton4.getText().equals("4")&&jButton5.getText().equals("5")&&jButton6.getText().equals("6")&&jButton7.getText().equals("7")&&jButton8.getText().equals("8")&&jButton9.getText().equals("9")&&jButton10.getText().equals("10")&&jButton11.getText().equals("11")&&jButton12.getText().equals("12")&&jButton13.getText().equals("13")&&jButton14.getText().equals("14")&&jButton15.getText().equals("15")){
    JOptionPane.showMessageDialog(this, "Ganaste \n No de intentos: "+intentos);
}
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        intentos++;
        System.out.println("Intento no: "+intentos);
        if(jButton7.isVisible()==false){
        jButton7.setText(jButton11.getText());
        jButton11.setVisible(false);
        jButton7.setVisible(true);
        }else if(jButton15.isVisible()==false){
        jButton15.setText(jButton11.getText());
        jButton11.setVisible(false);
        jButton15.setVisible(true);
        }else if(jButton12.isVisible()==false){
        jButton12.setText(jButton11.getText());
        jButton11.setVisible(false);
        jButton12.setVisible(true);
        }else if(jButton10.isVisible()==false){
        jButton10.setText(jButton11.getText());
        jButton11.setVisible(false);
        jButton10.setVisible(true);
        }
        
 if(jButton1.getText().equals("1")&&jButton2.getText().equals("2")&&jButton3.getText().equals("3")&&jButton4.getText().equals("4")){
    JOptionPane.showMessageDialog(this, "Linea 1 completa \n No de intentos: "+intentos);
}
if(jButton1.getText().equals("1")&&jButton2.getText().equals("2")&&jButton3.getText().equals("3")&&jButton4.getText().equals("4")){
    JOptionPane.showMessageDialog(this, "Linea 1 completa \n No de intentos: "+intentos);
}
if(jButton1.getText().equals("1")&&jButton2.getText().equals("2")&&jButton3.getText().equals("3")&&jButton4.getText().equals("4")&&jButton5.getText().equals("5")&&jButton6.getText().equals("6")&&jButton7.getText().equals("7")&&jButton8.getText().equals("8")&&jButton9.getText().equals("9")&&jButton10.getText().equals("10")&&jButton11.getText().equals("11")&&jButton12.getText().equals("12")&&jButton13.getText().equals("13")&&jButton14.getText().equals("14")&&jButton15.getText().equals("15")){
    JOptionPane.showMessageDialog(this, "Ganaste \n No de intentos: "+intentos);
}
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
        intentos++;
        System.out.println("Intento no: "+intentos);
        if(jButton9.isVisible()==false){
        jButton9.setText(jButton13.getText());
        jButton13.setVisible(false);
        jButton9.setVisible(true);
        }else if(jButton14.isVisible()==false){
        jButton14.setText(jButton13.getText());
        jButton13.setVisible(false);
        jButton14.setVisible(true);
        }
        
 if(jButton1.getText().equals("1")&&jButton2.getText().equals("2")&&jButton3.getText().equals("3")&&jButton4.getText().equals("4")){
    JOptionPane.showMessageDialog(this, "Linea 1 completa \n No de intentos: "+intentos);
}
if(jButton1.getText().equals("1")&&jButton2.getText().equals("2")&&jButton3.getText().equals("3")&&jButton4.getText().equals("4")&&jButton5.getText().equals("5")&&jButton6.getText().equals("6")&&jButton7.getText().equals("7")&&jButton8.getText().equals("8")&&jButton9.getText().equals("9")&&jButton10.getText().equals("10")&&jButton11.getText().equals("11")&&jButton12.getText().equals("12")&&jButton13.getText().equals("13")&&jButton14.getText().equals("14")&&jButton15.getText().equals("15")){
    JOptionPane.showMessageDialog(this, "Ganaste \n No de intentos: "+intentos);
}
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        intentos++;
        System.out.println("Intento no: "+intentos);
        if(jButton1.isVisible()==false){
        jButton1.setText(jButton5.getText());
        jButton5.setVisible(false);
        jButton1.setVisible(true);
        }else if(jButton9.isVisible()==false){
        jButton9.setText(jButton5.getText());
        jButton5.setVisible(false);
        jButton9.setVisible(true);
        }else if(jButton6.isVisible()==false){
        jButton6.setText(jButton5.getText());
        jButton5.setVisible(false);
        jButton6.setVisible(true);
        }
        
 if(jButton1.getText().equals("1")&&jButton2.getText().equals("2")&&jButton3.getText().equals("3")&&jButton4.getText().equals("4")){
    JOptionPane.showMessageDialog(this, "Linea 1 completa \n No de intentos: "+intentos);
}
if(jButton1.getText().equals("1")&&jButton2.getText().equals("2")&&jButton3.getText().equals("3")&&jButton4.getText().equals("4")&&jButton5.getText().equals("5")&&jButton6.getText().equals("6")&&jButton7.getText().equals("7")&&jButton8.getText().equals("8")&&jButton9.getText().equals("9")&&jButton10.getText().equals("10")&&jButton11.getText().equals("11")&&jButton12.getText().equals("12")&&jButton13.getText().equals("13")&&jButton14.getText().equals("14")&&jButton15.getText().equals("15")){
    JOptionPane.showMessageDialog(this, "Ganaste \n No de intentos: "+intentos);
}
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        intentos++;
        System.out.println("Intento no: "+intentos);
        if(jButton5.isVisible()==false){
        jButton5.setText(jButton6.getText());
        jButton6.setVisible(false);
        jButton5.setVisible(true);
        }else if(jButton7.isVisible()==false){
        jButton7.setText(jButton6.getText());
        jButton6.setVisible(false);
        jButton7.setVisible(true);
        }else if(jButton2.isVisible()==false){
        jButton2.setText(jButton6.getText());
        jButton6.setVisible(false);
        jButton2.setVisible(true);
        }else if(jButton10.isVisible()==false){
        jButton10.setText(jButton6.getText());
        jButton6.setVisible(false);
        jButton10.setVisible(true);
        }
        if(jButton1.getText().equals("1")&&jButton2.getText().equals("2")&&jButton3.getText().equals("3")&&jButton4.getText().equals("4")){
    JOptionPane.showMessageDialog(this, "Linea 1 completa \n No de intentos: "+intentos);
}
 if(jButton1.getText().equals("1")&&jButton2.getText().equals("2")&&jButton3.getText().equals("3")&&jButton4.getText().equals("4")){
    JOptionPane.showMessageDialog(this, "Linea 1 completa \n No de intentos: "+intentos);
}
if(jButton1.getText().equals("1")&&jButton2.getText().equals("2")&&jButton3.getText().equals("3")&&jButton4.getText().equals("4")&&jButton5.getText().equals("5")&&jButton6.getText().equals("6")&&jButton7.getText().equals("7")&&jButton8.getText().equals("8")&&jButton9.getText().equals("9")&&jButton10.getText().equals("10")&&jButton11.getText().equals("11")&&jButton12.getText().equals("12")&&jButton13.getText().equals("13")&&jButton14.getText().equals("14")&&jButton15.getText().equals("15")){
    JOptionPane.showMessageDialog(this, "Ganaste \n No de intentos: "+intentos);
}
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        intentos++;
        System.out.println("Intento no: "+intentos);
        if(jButton3.isVisible()==false){
        jButton3.setText(jButton7.getText());
        jButton7.setVisible(false);
        jButton3.setVisible(true);
        }else if(jButton11.isVisible()==false){
        jButton11.setText(jButton7.getText());
        jButton7.setVisible(false);
        jButton11.setVisible(true);
        }if(jButton8.isVisible()==false){
        jButton8.setText(jButton7.getText());
        jButton7.setVisible(false);
        jButton8.setVisible(true);
        }if(jButton6.isVisible()==false){
        jButton6.setText(jButton7.getText());
        jButton7.setVisible(false);
        jButton6.setVisible(true);
        }
        
 if(jButton1.getText().equals("1")&&jButton2.getText().equals("2")&&jButton3.getText().equals("3")&&jButton4.getText().equals("4")){
    JOptionPane.showMessageDialog(this, "Linea 1 completa \n No de intentos: "+intentos);
}
if(jButton1.getText().equals("1")&&jButton2.getText().equals("2")&&jButton3.getText().equals("3")&&jButton4.getText().equals("4")&&jButton5.getText().equals("5")&&jButton6.getText().equals("6")&&jButton7.getText().equals("7")&&jButton8.getText().equals("8")&&jButton9.getText().equals("9")&&jButton10.getText().equals("10")&&jButton11.getText().equals("11")&&jButton12.getText().equals("12")&&jButton13.getText().equals("13")&&jButton14.getText().equals("14")&&jButton15.getText().equals("15")){
    JOptionPane.showMessageDialog(this, "Ganaste \n No de intentos: "+intentos);
}
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        intentos++;
        System.out.println("Intento no: "+intentos);
        if(jButton4.isVisible()==false){
        jButton4.setText(jButton8.getText());
        jButton8.setVisible(false);
        jButton4.setVisible(true);
        }if(jButton7.isVisible()==false){
        jButton7.setText(jButton8.getText());
        jButton8.setVisible(false);
        jButton7.setVisible(true);
        }if(jButton12.isVisible()==false){
        jButton12.setText(jButton8.getText());
        jButton8.setVisible(false);
        jButton12.setVisible(true);
        }
        
 if(jButton1.getText().equals("1")&&jButton2.getText().equals("2")&&jButton3.getText().equals("3")&&jButton4.getText().equals("4")){
    JOptionPane.showMessageDialog(this, "Linea 1 completa \n No de intentos: "+intentos);
}
if(jButton1.getText().equals("1")&&jButton2.getText().equals("2")&&jButton3.getText().equals("3")&&jButton4.getText().equals("4")&&jButton5.getText().equals("5")&&jButton6.getText().equals("6")&&jButton7.getText().equals("7")&&jButton8.getText().equals("8")&&jButton9.getText().equals("9")&&jButton10.getText().equals("10")&&jButton11.getText().equals("11")&&jButton12.getText().equals("12")&&jButton13.getText().equals("13")&&jButton14.getText().equals("14")&&jButton15.getText().equals("15")){
    JOptionPane.showMessageDialog(this, "Ganaste \n No de intentos: "+intentos);
}
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        intentos++;
        System.out.println("Intento no: "+intentos);
        if(jButton1.isVisible()==false){
        jButton1.setText(jButton2.getText());
        jButton2.setVisible(false);
        jButton1.setVisible(true);
        }else if(jButton3.isVisible()==false){
        jButton3.setText(jButton2.getText());
        jButton2.setVisible(false);
        jButton3.setVisible(true);
        }else if(jButton6.isVisible()==false){
        jButton6.setText(jButton2.getText());
        jButton2.setVisible(false);
        jButton6.setVisible(true);
        }
        
 if(jButton1.getText().equals("1")&&jButton2.getText().equals("2")&&jButton3.getText().equals("3")&&jButton4.getText().equals("4")){
    JOptionPane.showMessageDialog(this, "Linea 1 completa \n No de intentos: "+intentos);
}
if(jButton1.getText().equals("1")&&jButton2.getText().equals("2")&&jButton3.getText().equals("3")&&jButton4.getText().equals("4")&&jButton5.getText().equals("5")&&jButton6.getText().equals("6")&&jButton7.getText().equals("7")&&jButton8.getText().equals("8")&&jButton9.getText().equals("9")&&jButton10.getText().equals("10")&&jButton11.getText().equals("11")&&jButton12.getText().equals("12")&&jButton13.getText().equals("13")&&jButton14.getText().equals("14")&&jButton15.getText().equals("15")){
    JOptionPane.showMessageDialog(this, "Ganaste \n No de intentos: "+intentos);
}
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        intentos++;
        System.out.println("Intento no: "+intentos);
        if(jButton2.isVisible()==false){
        jButton2.setText(jButton3.getText());
        jButton3.setVisible(false);
        jButton2.setVisible(true);
        }else if(jButton4.isVisible()==false){
        jButton4.setText(jButton3.getText());
        jButton3.setVisible(false);
        jButton4.setVisible(true);
        }else if(jButton7.isVisible()==false){
        jButton7.setText(jButton3.getText());
        jButton3.setVisible(false);
        jButton7.setVisible(true);
        }
        
 if(jButton1.getText().equals("1")&&jButton2.getText().equals("2")&&jButton3.getText().equals("3")&&jButton4.getText().equals("4")){
    JOptionPane.showMessageDialog(this, "Linea 1 completa \n No de intentos: "+intentos);
}
if(jButton1.getText().equals("1")&&jButton2.getText().equals("2")&&jButton3.getText().equals("3")&&jButton4.getText().equals("4")&&jButton5.getText().equals("5")&&jButton6.getText().equals("6")&&jButton7.getText().equals("7")&&jButton8.getText().equals("8")&&jButton9.getText().equals("9")&&jButton10.getText().equals("10")&&jButton11.getText().equals("11")&&jButton12.getText().equals("12")&&jButton13.getText().equals("13")&&jButton14.getText().equals("14")&&jButton15.getText().equals("15")){
    JOptionPane.showMessageDialog(this, "Ganaste \n No de intentos: "+intentos);
}
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        intentos++;
        System.out.println("Intento no: "+intentos);
        if(jButton3.isVisible()==false){
        jButton3.setText(jButton4.getText());
        jButton4.setVisible(false);
        jButton3.setVisible(true);
        }else if(jButton8.isVisible()==false){
        jButton8.setText(jButton4.getText());
        jButton4.setVisible(false);
        jButton8.setVisible(true);
        }
        
 if(jButton1.getText().equals("1")&&jButton2.getText().equals("2")&&jButton3.getText().equals("3")&&jButton4.getText().equals("4")){
    JOptionPane.showMessageDialog(this, "Linea 1 completa \n No de intentos: "+intentos);
}
if(jButton1.getText().equals("1")&&jButton2.getText().equals("2")&&jButton3.getText().equals("3")&&jButton4.getText().equals("4")&&jButton5.getText().equals("5")&&jButton6.getText().equals("6")&&jButton7.getText().equals("7")&&jButton8.getText().equals("8")&&jButton9.getText().equals("9")&&jButton10.getText().equals("10")&&jButton11.getText().equals("11")&&jButton12.getText().equals("12")&&jButton13.getText().equals("13")&&jButton14.getText().equals("14")&&jButton15.getText().equals("15")){
    JOptionPane.showMessageDialog(this, "Ganaste \n No de intentos: "+intentos);
}
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        // TODO add your handling code here:
                jButton16.setVisible(false);
        Random generadorAleatorios = new Random();
        int arre[]=new int[15];
        int t=0;
    int cont;
    int i,comp=0;
    cont=0;
while(t<=100){    
    int numeroAleatorio = 1+generadorAleatorios.nextInt(15);
    if(t==0){
        arre[cont]=numeroAleatorio;
        System.out.println(t+" no: "+arre[cont]);
        cont++;
    }else if(t>0){
        for(i=0;i<=cont;i++){
            if(numeroAleatorio==arre[i]){
                comp=1;
            }
        }
        if(comp==0){
            arre[cont]=numeroAleatorio;
            System.out.println(cont+" no: "+arre[cont]);
            comp=0;      
            cont++;
            if(cont==15){
                t=100;
            }
        }
        comp=0;
    }
  t++;
}
jButton1.setText(Integer.toString(arre[0]));
jButton2.setText(Integer.toString(arre[1]));
jButton3.setText(Integer.toString(arre[2]));
jButton4.setText(Integer.toString(arre[3]));
jButton5.setText(Integer.toString(arre[4]));
jButton6.setText(Integer.toString(arre[5]));
jButton7.setText(Integer.toString(arre[6]));
jButton8.setText(Integer.toString(arre[7]));
jButton9.setText(Integer.toString(arre[8]));
jButton10.setText(Integer.toString(arre[9]));
jButton11.setText(Integer.toString(arre[10]));
jButton12.setText(Integer.toString(arre[11]));
jButton13.setText(Integer.toString(arre[12]));
jButton14.setText(Integer.toString(arre[13]));
jButton15.setText(Integer.toString(arre[14]));

jButton1.setVisible(true);
jButton2.setVisible(true);
jButton3.setVisible(true);
jButton4.setVisible(true);
jButton5.setVisible(true);
jButton6.setVisible(true);
jButton7.setVisible(true);
jButton8.setVisible(true);
jButton9.setVisible(true);
jButton10.setVisible(true);
jButton11.setVisible(true);
jButton12.setVisible(true);
jButton13.setVisible(true);
jButton14.setVisible(true);
jButton15.setVisible(true);
    }//GEN-LAST:event_jButton17ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cuadro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cuadro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cuadro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cuadro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cuadro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
